version: '3.8'

services:
  member-service:
    image: 2214yj/soup-member-service-no-log:latest
    container_name: soup-member-service
    ports:
      - '8002:8002'
    environment:
      spring.datasource.url: jdbc:mysql://soup-mysql:3306/soup?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: pass123#
      spring.redis.host: soup-redis
      spring.redis.port: 6379
      jwt.access-token.expire-length: 36000000
      jwt.refresh-token.expire-length: 12096000000
    networks:
      - backend-db
      - frontend-backend

  admin-service:
    image: 2214yj/soup-admin-service-no-log:latest
    container_name: soup-admin-service
    ports:
      - '8001:8001'
    environment:
      spring.datasource.url: jdbc:mysql://soup-mysql:3306/soup?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: pass123#
      jwt.access-token.expire-length: 36000000
      jwt.refresh-token.expire-length: 12096000000
    networks:
      - backend-db
      - frontend-backend

  search-service:
    image: 2214yj/soup-search-service-no-log:latest
    container_name: soup-search-service
    ports:
      - '8000:8000'
    environment:
      spring.datasource.url: jdbc:mysql://soup-mysql:3306/soup?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: pass123#
      elasticsearch.host: soup-elasticsearch
      elasticsearch.port: 9200
      jwt.access-token.expire-length: 36000000
      jwt.refresh-token.expire-length: 12096000000
    networks:
      - backend-db
      - frontend-backend

  frontend:
    image: aramu/soup-frontend-msa:2.0
    container_name: soup-frontend
    ports:
      - '3000:3000'
    environment:
      MEMBER_URI: soup-member-service:8002
      ADMIN_URI: soup-admin-service:8001
      SEARCH_URI: soup-search-service:8000
    networks:
      - frontend-backend


networks:
  frontend-backend:
    name: frontend-backend
  backend-db:
    external:
      true
